// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEntertainmentSystem.Data.Access;

#nullable disable

namespace MyEntertainmentSystem.Data.Access.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20240629003948_Updating Migration for Hobby Data Model")]
    partial class UpdatingMigrationforHobbyDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyEntertainmentSystem.Data.Entities.HobbyCategories.Hobbies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompletionState")
                        .HasColumnType("int");

                    b.Property<string>("Episodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Featured")
                        .HasColumnType("bit");

                    b.Property<int>("HobbyType")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");
                });

            modelBuilder.Entity("MyEntertainmentSystem.Data.Entities.HobbyCategories.Summary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HobbiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HobbiesId");

                    b.ToTable("Summary");
                });

            modelBuilder.Entity("MyEntertainmentSystem.Data.Entities.HobbyCategories.Summary", b =>
                {
                    b.HasOne("MyEntertainmentSystem.Data.Entities.HobbyCategories.Hobbies", null)
                        .WithMany("Description")
                        .HasForeignKey("HobbiesId");
                });

            modelBuilder.Entity("MyEntertainmentSystem.Data.Entities.HobbyCategories.Hobbies", b =>
                {
                    b.Navigation("Description");
                });
#pragma warning restore 612, 618
        }
    }
}
